pipeline {
    agent any
    environment {
        APP_NAME = 'small-tools-web'
        APP_PROFILE = 'dev'
        APP_IMAGE = 'registry.cn-hangzhou.aliyuncs.com/zhengqing/small-tools-web:dev'
        APP_PORT = 88
    }

    stages {

        stage('vue环境准备') {
            steps {
                echo '****************************** vue start... ******************************'
                sh 'pwd'
                // 根据jenkins构建时，是否需要cd ...
                sh 'cd small-tools-web && pwd && cnpm install && cnpm run build:$APP_PROFILE'
            }
        }

        stage('构建Docker镜像') {
            steps {
                echo '****************************** delete container and image... ******************************'
                sh 'docker ps -a | grep $APP_NAME | awk \'{print $1}\' | xargs docker stop {} | xargs docker rm {}'
                sh 'docker images | grep $APP_NAME | grep dev|awk \'{print $3}\' | xargs docker rmi'

                echo '****************************** build image... ******************************'
                // -f:指定Dockerfile文件路径
                sh 'docker build -f Dockerfile --build-arg PROFILE=$APP_PROFILE -t $APP_IMAGE . --no-cache'
            }
        }

        stage('运行容器') {
            steps {
                echo '****************************** run start... ******************************'
                sh 'docker run -d -p $APP_PORT:80 --restart=always --name $APP_NAME $APP_IMAGE'
            }
        }

    }
}
